### ISSUE TITLE
Missing required arguments ? 

### ISSUE THREAD

**Issue by Enescigdem** [JuanFMontesinos/Acappella-YNet#2]
Hello, thanks for this great work and dataset,
When I tried to run ,I got error below,
Traceback (most recent call last):
  File "Desktop/Acappella-YNet/run.py", line 27, in <module>
    iter_param, model, model_kwargs = VnBSS.ModelConstructor(
  File "/Desktop/Acappella-YNet/VnBSS/models/__init__.py", line 134, in build
    return self._build_dev()
  File "/Desktop/Acappella-YNet/VnBSS/models/__init__.py", line 140, in _build_dev
    model = constructor(**self.common_kwargs)
TypeError: __init__() missing 6 required keyword-only arguments: 'remix_input', 'remix_coef', 'video_enabled', 'llcp_enabled', 'skeleton_enabled', and 'activation'

**Comment by JuanFMontesinos** [comment]
Hi,
May I know which command did you use to run the code?

**Comment by Enescigdem** [comment]
Hi,
This is exactly te same format in the README. 
python run.py -m model_name --workname experiment_name --arxiv_path directory_of_experiments --pretrained_from path_pret_weights

**Comment by Enescigdem** [comment]
Could you please tell me the correct way for training from  scratch ?

**Comment by JuanFMontesinos** [comment]
Hi, should be fixed at f05d89e 
We are basically wondering how to give an easy acess to the dataset as you cannot run the code without it. 
Whether doing a mock up dataset so that code can be debugged or just uploading processed files. 

I accidentally deleted few lines while removing irrelevant pieces of code.

**Comment by Enescigdem** [comment]
I cloned this GitHub repo 2 days ago so I must be using the newest version. I preprocessed the first 200 data files by using preproc/preprocess.py. Then tried to run just to see the pipeline of the system. 
So sorry I did not get your point . What is wrong with my trial?

**Comment by JuanFMontesinos** [comment]
Sorry i commited this after your issue. So you should clone it again.
I just basically meant the code will stuck if you have no dataset.

We are gonna upload a mock up dataset within few hours so that the code can be debugged without having a dataset. 
If you clone the new code, please remember to set the dataset paths at config>dataset_paths.json

**Comment by Enescigdem** [comment]
Should I RE-run the preprocess.py ?
Thank you for fast reply,

**Comment by JuanFMontesinos** [comment]
Yes,
you can double check the dataset structure at
https://github.com/JuanFMontesinos/Acappella-YNet/tree/main/VnBSS

**Comment by Enescigdem** [comment]
Thanks to your help . I could run the preprocessing without error.
